const Types = {
    USER: "USER",
    ADMIN: "ADMIN",
    MARCAR_PONTO: "MARCA_PONTO",
    VER_ESPELHO: "VER_ESPELHO",
    DOWNLOAD_ESPELHO: "DOWNLOAD_ESPELHO",
    CONFIGURACOES: "CONFIGURAÇÕES",
    CADASTRO_SETOR: "CADASTRO_SETOR",
};

export default Types;
